--
-- テストに使用するOracleDBユーザを作成する
--

-- USER SQL
CREATE USER "MYTEST" IDENTIFIED BY "MYTEST"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "MYTEST" ;
GRANT CREATE SESSION TO MYTEST;
